# This workflow will install Python dependencies, run tests

name: GitHub Actions Parallel Run of Django Company API tests and Fibonacci tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  DjangoAPI-Test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv --upgrade
        pipenv install --system
    - name: Test with pytest
      env:
        PYTHONPATH: ${{ secrets.PYTHONPATH }}
        DJANGO_SETTINGS_MODULE: ${{ secrets.DJANGO_SETTINGS_MODULE }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
      run: |
        echo $PYTHONPATH
        echo $DJANGO_SETTINGS_MODULE
        echo $SECRET_KEY
        echo $EMAIL_HOST_PASSWORD
        pytest api/coronavstech -s -v --durations=0 --cov=.
  Fibonacci-Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv --upgrade
          pipenv install --system
      - name: Test with pytest
        env:
          PYTHONPATH: ${{ secrets.PYTHONPATH }}
          DJANGO_SETTINGS_MODULE: ${{ secrets.DJANGO_SETTINGS_MODULE }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
        run: |
          echo $PYTHONPATH
          echo $DJANGO_SETTINGS_MODULE
          echo $SECRET_KEY
          echo $EMAIL_HOST_PASSWORD
          pytest fibonacci -s -v --durations=0 --cov=.